spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micronomina
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8081


  # security
jwt:
  secret: secret
  expiration: 360000
